#!/usr/bin/env python3
"""whole-team project helper. Python 3.9+ standard library only.

Commands:
  init       create .whole-team.json and the profile's documents (never overwrites)
  status     stories by status, WIP, next story, blocked stories, handover, placeholders
  lint       check stories, dependencies, requirement coverage and required documents
  kanban     write docs/05-planning/KANBAN.md from USER_STORIES.md
  sprint     report for a sprint: planned, shipped, not done (for the close)
  agreement  print the working agreement block filled from .whole-team.json

Run from anywhere inside the project; the root is the nearest directory holding
.whole-team.json, else the git root, else the current directory.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

CONFIG_NAME = ".whole-team.json"
TEMPLATES = Path(__file__).resolve().parent.parent / "templates"
STORIES_PATH = "docs/05-planning/USER_STORIES.md"
REQUIREMENTS_PATH = "docs/02-requirements/REQUIREMENTS.md"
KANBAN_PATH = "docs/05-planning/KANBAN.md"
INDEX_PATH = "docs/README.md"
RETROS_PATH = "docs/05-planning/RETROSPECTIVES.md"
PLACEHOLDER = "TODO(whole-team)"

STATUSES = ("Not started", "In progress", "In review", "Done", "Dropped")
PRIORITIES = ("MUST", "SHOULD", "COULD", "DEFERRED")
PROFILES = ("lite", "standard", "strict")
BOARDS = ("github", "linear", "jira", "notion", "local")
CHECKPOINTS = ("every-step", "phase", "gates")

# (project path, template name). A template of None means generated by this script.
LITE_DOCS: List[Tuple[str, Optional[str]]] = [
    ("SCOPE.md", "SCOPE.md"),
    ("CHANGELOG.md", "CHANGELOG.md"),
    ("docs/03-architecture/ARCHITECTURE.md", "ARCHITECTURE.md"),
    (STORIES_PATH, "USER_STORIES.md"),
    ("docs/05-planning/DEFINITION_OF_DONE.md", "DEFINITION_OF_DONE.md"),
]
STANDARD_DOCS = LITE_DOCS + [
    (INDEX_PATH, None),
    (REQUIREMENTS_PATH, "REQUIREMENTS.md"),
    ("docs/03-architecture/decisions/ADR-0000-template.md", "ADR.md"),
    ("docs/02-requirements/USE_CASES.md", "USE_CASES.md"),
    ("docs/05-planning/SPRINTS.md", "SPRINTS.md"),
    (RETROS_PATH, "RETROSPECTIVES.md"),
    ("docs/06-security/THREAT_MODEL.md", "THREAT_MODEL.md"),
    ("docs/07-testing/TEST_STRATEGY.md", "TEST_STRATEGY.md"),
    ("RELEASE_NOTES.md", "RELEASE_NOTES.md"),
]
STRICT_DOCS = STANDARD_DOCS + [
    ("docs/08-operations/OPERATIONS.md", "OPERATIONS.md"),
    ("docs/09-uat/UAT_PLAN.md", "UAT_PLAN.md"),
    ("docs/10-reviews/TRACEABILITY.md", "TRACEABILITY.md"),
]
UI_DOCS = [("docs/04-design/DESIGN.md", "DESIGN.md")]
BRIEF_DOCS = [("docs/01-discovery/BRIEF_ANALYSIS.md", "BRIEF_ANALYSIS.md")]
ASSESSMENT_DOCS = BRIEF_DOCS + [
    ("docs/10-reviews/TRACEABILITY.md", "TRACEABILITY.md"),
    ("AI_USAGE.md", "AI_USAGE.md"),
]

STORY_HEADING = re.compile(r"^###\s+(US-\d+)\s*:\s*(.+?)\s*$")
EPIC_HEADING = re.compile(r"^##\s+(?!#)(.+?)\s*$")
STORY_ID = re.compile(r"\bUS-\d+\b")
REQ_ID = re.compile(r"\b[A-Z]{2,4}-\d{3}\b")
REQ_ROW = re.compile(r"^\|\s*([A-Z]{2,4}-\d{3})\s*\|")
REQ_HEADING = re.compile(r"^#{2,4}\s+([A-Z]{2,4}-\d{3})\b")
STORY_SHAPE = re.compile(r"^As an? .+?, I want .+?, so that .+", re.IGNORECASE)
FENCE = re.compile(r"^\s*(```|~~~)")
FIELD_END = r"(?=\s*[·|]|\s*$)"


def field_value(block: str, name: str) -> Optional[str]:
    match = re.search(rf"{name}:[ \t]*(.*?){FIELD_END}", block, re.MULTILINE)
    return match.group(1).strip() if match else None


@dataclass
class Story:
    id: str
    title: str
    epic: str
    line: int
    priority: Optional[str] = None
    sprint: Optional[str] = None
    status: Optional[str] = None
    depends: List[str] = field(default_factory=list)
    requirements: List[str] = field(default_factory=list)
    tests: Optional[str] = None
    has_criteria: bool = False

    @property
    def sprint_number(self) -> float:
        try:
            return float(self.sprint or "")
        except ValueError:
            return float("inf")

    def in_sprint(self, number: object) -> bool:
        """True when this story's sprint equals `number`, so "01", "1" and 1.0 all match sprint 1."""
        try:
            return self.sprint_number == float(str(number))
        except ValueError:
            return False

    @property
    def short_title(self) -> str:
        match = re.search(r"I want (?:to )?(.+?), so that", self.title, re.IGNORECASE)
        return match.group(1) if match else self.title


def dependency_cycles(by_id: Dict[str, Story]) -> List[List[str]]:
    """Each dependency cycle once, as a path that ends where it starts (US-001 -> US-002 -> US-001)."""
    cycles: List[List[str]] = []
    done: set = set()

    def visit(story_id: str, stack: List[str]) -> None:
        if story_id in stack:
            cycles.append(stack[stack.index(story_id):] + [story_id])
            return
        if story_id in done or story_id not in by_id:
            return
        stack.append(story_id)
        for dep in by_id[story_id].depends:
            if dep != story_id:
                visit(dep, stack)
        stack.pop()
        done.add(story_id)

    for story_id in by_id:
        visit(story_id, [])
    return cycles


def parse_stories(text: str) -> List[Story]:
    stories: List[Story] = []
    epic = ""
    current: Optional[Story] = None
    block: List[str] = []

    def finish() -> None:
        if current is None:
            return
        body = "\n".join(block)
        current.priority = field_value(body, "Priority")
        current.sprint = field_value(body, "Sprint")
        current.status = field_value(body, "Status")
        depends = field_value(body, "Depends on") or ""
        current.depends = STORY_ID.findall(depends)
        reqs = field_value(body, "Requirements") or ""
        current.requirements = REQ_ID.findall(reqs)
        tests = re.search(r"^\s*-\s*Tests:[ \t]*(.*)$", body, re.MULTILINE)
        current.tests = tests.group(1).strip() if tests else None
        criteria = re.search(
            r"^\s*-\s*Acceptance criteria:[ \t]*(.*?)(?=^\s*-\s*Priority:|\Z)",
            body,
            re.MULTILINE | re.DOTALL,
        )
        if criteria:
            content = re.sub(r"[\s\-*]", "", criteria.group(1))
            current.has_criteria = bool(content)
        stories.append(current)

    in_fence = False
    for number, line in enumerate(text.splitlines(), start=1):
        if FENCE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        heading = STORY_HEADING.match(line)
        if heading:
            finish()
            current = Story(id=heading.group(1), title=heading.group(2), epic=epic, line=number)
            block = []
            continue
        epic_match = EPIC_HEADING.match(line)
        if epic_match:
            finish()
            current = None
            block = []
            epic = epic_match.group(1)
            continue
        if current is not None:
            block.append(line)
    finish()
    return stories


def parse_requirements(text: str) -> Dict[str, bool]:
    """Map requirement ID to whether it needs story coverage.

    Dropped requirements and unfilled template rows (still holding a
    placeholder) do not need coverage.
    """
    found: Dict[str, bool] = {}
    for line in text.splitlines():
        match = REQ_ROW.match(line) or REQ_HEADING.match(line)
        if match:
            found[match.group(1)] = "dropped" not in line.lower() and PLACEHOLDER not in line
    return found


def normalize_sprint_length(value: str) -> str:
    """'7' -> '7 days', '1' -> '1 day'; text such as '2 weeks' is kept."""
    value = value.strip()
    if value.isdigit():
        return f"{value} day" if value == "1" else f"{value} days"
    return value


def find_root(start: Path) -> Path:
    for directory in [start, *start.parents]:
        if (directory / CONFIG_NAME).is_file():
            return directory
    for directory in [start, *start.parents]:
        if (directory / ".git").exists():
            return directory
    return start


def load_config(root: Path) -> Optional[dict]:
    path = root / CONFIG_NAME
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise SystemExit(f"error: {CONFIG_NAME} is not valid JSON: {error}")


def required_docs(config: dict) -> List[Tuple[str, Optional[str]]]:
    profile = config.get("profile", "standard")
    docs = {"lite": LITE_DOCS, "standard": STANDARD_DOCS, "strict": STRICT_DOCS}.get(profile, STANDARD_DOCS)
    result = list(docs)
    if config.get("ui"):
        result += UI_DOCS
    if config.get("brief"):
        result += BRIEF_DOCS
    if config.get("assessment"):
        result += ASSESSMENT_DOCS
    seen: Dict[str, Optional[str]] = {}
    for path, template in result:
        seen.setdefault(path, template)
    return list(seen.items())


def read(root: Path, relative: str) -> Optional[str]:
    path = root / relative
    return path.read_text(encoding="utf-8") if path.is_file() else None


def docs_index(docs: Sequence[Tuple[str, Optional[str]]], existing: str = "") -> str:
    """Build docs/README.md from the profile's documents.

    Statuses already set in `existing` are kept, and rows the owner added for
    other documents are kept after the generated ones.
    """
    kept: Dict[str, str] = {}
    extra: List[str] = []
    listed = {path for path, _ in docs}
    for line in existing.splitlines():
        row = re.match(r"^\|\s*\[([^\]]+)\]\([^)]*\)\s*\|\s*([^|]+?)\s*\|", line)
        if not row:
            continue
        if row.group(1) in listed:
            kept[row.group(1)] = row.group(2)
        else:
            extra.append(line)
    lines = [
        "# Documentation",
        "",
        'Every document listed here exists and describes what exists. Status is "written" or "to be written"; keep it truthful.',
        "",
        "| Document | Status |",
        "|----------|--------|",
    ]
    for path, _ in docs:
        if path == INDEX_PATH:
            continue
        link = path[len("docs/"):] if path.startswith("docs/") else f"../{path}"
        lines.append(f"| [{path}]({link}) | {kept.get(path, 'to be written')} |")
    lines += extra
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- commands


def new_config(args: argparse.Namespace) -> dict:
    return {
        "version": 1,
        "profile": args.profile or "standard",
        "ui": args.ui,
        "brief": args.brief,
        "assessment": args.assessment,
        "board": {"tool": args.board or "local"},
        "branches": {"integration": "main" if args.trunk else "dev", "release": "main", "story": "feat/us-{id}-{slug}"},
        "sprint": {"length": normalize_sprint_length(args.sprint_length or "1 day"), "current": 1},
        "wip_limit": 2,
        "checkpoints": args.checkpoints or "every-step",
        "viewports": [390, 1024, 1280] if args.ui else [],
        "freeze": {"release": False},
    }


def update_config(config: dict, args: argparse.Namespace) -> List[str]:
    """Apply flags given on a re-run of init. Returns the changes made."""
    changes: List[str] = []
    if args.profile and args.profile != config.get("profile"):
        changes.append(f"profile {config.get('profile')} -> {args.profile}")
        config["profile"] = args.profile
    for flag in ("ui", "brief", "assessment"):
        if getattr(args, flag) and not config.get(flag):
            changes.append(f"{flag} on")
            config[flag] = True
    if args.ui and not config.get("viewports"):
        config["viewports"] = [390, 1024, 1280]
    board = config.setdefault("board", {})
    if args.board and args.board != board.get("tool"):
        changes.append(f"board {board.get('tool')} -> {args.board} (board identifiers kept; update them by hand)")
        board["tool"] = args.board
    branches = config.setdefault("branches", {})
    if args.trunk and branches.get("integration") != "main":
        changes.append(f"integration branch {branches.get('integration')} -> main (trunk-based)")
        branches["integration"] = "main"
    if args.checkpoints and args.checkpoints != config.get("checkpoints", "every-step"):
        changes.append(f"checkpoints {config.get('checkpoints', 'every-step')} -> {args.checkpoints}")
        config["checkpoints"] = args.checkpoints
    sprint = config.setdefault("sprint", {})
    if args.sprint_length:
        length = normalize_sprint_length(args.sprint_length)
        if length != sprint.get("length"):
            changes.append(f"sprint length {sprint.get('length')} -> {length}")
            sprint["length"] = length
    return changes


def cmd_init(args: argparse.Namespace) -> int:
    root = Path(args.dir).resolve()
    config_path = root / CONFIG_NAME
    if config_path.exists():
        config = load_config(root) or {}
        changes = update_config(config, args)
        if changes:
            config_path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
            print(f"updated  {CONFIG_NAME}: {'; '.join(changes)}")
        else:
            print(f"{CONFIG_NAME} exists; keeping it. Creating any missing documents for profile '{config.get('profile')}'.")
    else:
        config = new_config(args)
        config_path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")
        print(f"created  {CONFIG_NAME}")

    docs = required_docs(config)
    for relative, template in docs:
        target = root / relative
        if template is None:
            existed = target.exists()
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(docs_index(docs, target.read_text(encoding="utf-8") if existed else ""), encoding="utf-8")
            print(f"{'updated ' if existed else 'created '} {relative}")
            continue
        if target.exists():
            print(f"exists   {relative}")
            continue
        source = TEMPLATES / template
        if not source.is_file():
            print(f"missing template {template}; skipped {relative}", file=sys.stderr)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(source.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"created  {relative}")
    print("\nNext: fill the TODO(whole-team) markers, add the working agreement (wt.py agreement), connect the board.")
    return 0


def next_story(stories: Sequence[Story]) -> Tuple[Optional[Story], List[Tuple[Story, List[str]]]]:
    by_id = {story.id: story for story in stories}
    rank = {priority: index for index, priority in enumerate(PRIORITIES)}
    candidates: List[Story] = []
    blocked: List[Tuple[Story, List[str]]] = []
    for story in stories:
        if story.status != "Not started" or story.priority == "DEFERRED" or story.sprint_number == float("inf"):
            continue  # backlog stories are pulled only through sprint planning
        waiting = [dep for dep in story.depends if by_id.get(dep) is None or by_id[dep].status != "Done"]
        if waiting:
            blocked.append((story, waiting))
        else:
            candidates.append(story)
    candidates.sort(key=lambda s: (s.sprint_number, rank.get(s.priority or "", 9), int(s.id.split("-")[1])))
    return (candidates[0] if candidates else None), blocked


def placeholder_counts(root: Path, docs: Sequence[Tuple[str, Optional[str]]]) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for relative, _ in docs:
        text = read(root, relative)
        if text and PLACEHOLDER in text:
            counts[relative] = text.count(PLACEHOLDER)
    return counts


def open_handover(root: Path) -> Optional[str]:
    text = read(root, "CHANGELOG.md") or ""
    for line in text.splitlines():
        stripped = line.strip().lstrip("-* ").strip()
        if stripped.lower().startswith("handover") and "(resolved)" not in stripped.lower():
            return stripped
    return None


def open_retro_actions(root: Path) -> int:
    """Unchecked action items in the retrospectives, outside the template comment."""
    text = read(root, RETROS_PATH) or ""
    text = re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL)
    return len(re.findall(r"^\s*-\s*\[ \]\s*\S", text, re.MULTILINE))


def cmd_status(args: argparse.Namespace) -> int:
    root = find_root(Path.cwd())
    config = load_config(root)
    if config is None:
        print(f"No {CONFIG_NAME} in {root}. Start with intake (reference/intake.md), then run: wt.py init --profile <lite|standard|strict>")
        return 0
    board = config.get("board", {}).get("tool", "local")
    sprint = config.get("sprint", {}).get("current", "?")
    frozen = " · release branch FROZEN" if config.get("freeze", {}).get("release") else ""
    checkpoints = config.get("checkpoints", "every-step")
    print(f"whole-team · profile {config.get('profile')} · board {board} · sprint {sprint} · checkpoints {checkpoints}{frozen}")

    text = read(root, STORIES_PATH)
    if text is None:
        print(f"No {STORIES_PATH} yet.")
        return 0
    stories = parse_stories(text)
    counts = {status: 0 for status in STATUSES}
    for story in stories:
        if story.status in counts:
            counts[story.status] += 1
    summary = " · ".join(f"{name} {count}" for name, count in counts.items() if count)
    print(f"Stories: {len(stories)} total" + (f" · {summary}" if summary else ""))
    musts = [s for s in stories if s.priority == "MUST" and s.status != "Dropped"]
    if musts:
        done = sum(1 for s in musts if s.status == "Done")
        print(f"MUST done: {done}/{len(musts)}")

    in_sprint = [s for s in stories if s.in_sprint(sprint) and s.status != "Dropped"]
    if in_sprint:
        done = sum(1 for s in in_sprint if s.status == "Done")
        print(f"Sprint {sprint}: {done}/{len(in_sprint)} stories done")

    active = [s for s in stories if s.status in ("In progress", "In review")]
    limit = int(config.get("wip_limit", 2))
    for story in active:
        print(f"{story.status}: {story.id} {story.short_title}")
    if len(active) > limit:
        print(f"WIP {len(active)} is over the limit of {limit}: finish before starting another.")

    upcoming, blocked = next_story(stories)
    if upcoming:
        print(f"Next up: {upcoming.id} {upcoming.short_title} (sprint {upcoming.sprint}, {upcoming.priority})")
    elif not active:
        print("Next up: nothing ready. Plan the next stories or close the sprint.")
    for story, waiting in blocked:
        print(f"Blocked: {story.id} waits on {', '.join(waiting)}")

    handover = open_handover(root)
    if handover:
        print(f"Handover: {handover}")
    actions = open_retro_actions(root)
    if actions:
        print(f"Retro actions open: {actions} (check them at sprint planning)")
    placeholders = placeholder_counts(root, required_docs(config))
    if placeholders:
        total = sum(placeholders.values())
        print(f"Docs: {total} placeholder(s) to fill in {len(placeholders)} file(s)")
    return 0


def lint(root: Path, config: dict, release: bool) -> Tuple[List[str], List[str]]:
    errors: List[str] = []
    warnings: List[str] = []
    docs = required_docs(config)
    for relative, _ in docs:
        if not (root / relative).exists():
            errors.append(f"{relative}: missing (required by profile '{config.get('profile')}'); run wt.py init")

    text = read(root, STORIES_PATH)
    stories = parse_stories(text) if text else []
    by_id: Dict[str, Story] = {}
    for story in stories:
        where = f"{STORIES_PATH}:{story.line} {story.id}"
        if story.id in by_id:
            errors.append(f"{where}: duplicate ID (first at line {by_id[story.id].line})")
            continue
        by_id[story.id] = story
        if not STORY_SHAPE.match(story.title):
            warnings.append(f"{where}: title is not 'As a <persona>, I want <capability>, so that <value>.'")
        if not story.has_criteria:
            errors.append(f"{where}: no acceptance criteria")
        hint = " (separate fields with ' · ', for example 'Priority: MUST · Sprint: 1 · Status: Not started')"
        if story.priority not in PRIORITIES:
            extra = hint if story.priority and ("," in story.priority or ":" in story.priority) else ""
            errors.append(f"{where}: priority '{story.priority}' is not one of {', '.join(PRIORITIES)}{extra}")
        if story.status not in STATUSES:
            extra = hint if story.status and ("," in story.status or ":" in story.status) else ""
            errors.append(f"{where}: status '{story.status}' is not one of {', '.join(STATUSES)}{extra}")
        if story.status == "Done" and not story.tests:
            errors.append(f"{where}: Done but the Tests line is empty")

    for story in by_id.values():
        where = f"{STORIES_PATH}:{story.line} {story.id}"
        for dep in story.depends:
            if dep == story.id:
                errors.append(f"{where}: depends on itself")
            elif dep not in by_id:
                errors.append(f"{where}: depends on unknown {dep}")
            elif story.status == "Done" and by_id[dep].status != "Done":
                errors.append(f"{where}: Done but its dependency {dep} is {by_id[dep].status}")
    for cycle in dependency_cycles(by_id):
        errors.append(f"{STORIES_PATH}: dependency cycle {' -> '.join(cycle)}; no story in it can start")

    limit = int(config.get("wip_limit", 2))
    active = [s.id for s in by_id.values() if s.status in ("In progress", "In review")]
    if len(active) > limit:
        warnings.append(f"WIP {len(active)} ({', '.join(active)}) is over the limit of {limit}")

    requirements_text = read(root, REQUIREMENTS_PATH)
    if requirements_text is not None:
        defined = parse_requirements(requirements_text)
        used = set()
        for story in by_id.values():
            for req in story.requirements:
                if req not in defined:
                    errors.append(f"{STORIES_PATH}:{story.line} {story.id}: references {req}, not defined in {REQUIREMENTS_PATH}")
                if story.status != "Dropped":
                    used.add(req)
        for req, active_req in defined.items():
            if active_req and req not in used:
                message = f"{REQUIREMENTS_PATH}: {req} is not covered by any story"
                (errors if release else warnings).append(message)

    for relative, count in placeholder_counts(root, docs).items():
        message = f"{relative}: {count} {PLACEHOLDER} placeholder(s) left"
        (errors if release else warnings).append(message)

    changelog = read(root, "CHANGELOG.md") or ""
    if re.search(r"board sync pending", changelog, re.IGNORECASE):
        message = "CHANGELOG.md: 'Board sync pending' entry not cleared"
        (errors if release else warnings).append(message)

    if release:
        for story in by_id.values():
            if story.priority == "MUST" and story.status not in ("Done", "Dropped"):
                errors.append(f"{story.id}: MUST story is {story.status}")
            elif story.status in ("In progress", "In review"):
                errors.append(f"{story.id}: {story.status} at release")
        if open_handover(root):
            errors.append("CHANGELOG.md: open Handover line; finish the work or mark it (resolved)")
    return errors, warnings


def cmd_lint(args: argparse.Namespace) -> int:
    root = find_root(Path.cwd())
    config = load_config(root)
    if config is None:
        print(f"error: no {CONFIG_NAME} found; run wt.py init first")
        return 1
    errors, warnings = lint(root, config, args.release)
    for message in errors:
        print(f"error    {message}")
    for message in warnings:
        print(f"warning  {message}")
    mode = "release lint" if args.release else "lint"
    print(f"{mode}: {len(errors)} error(s), {len(warnings)} warning(s)")
    return 1 if errors else 0


def cmd_kanban(args: argparse.Namespace) -> int:
    root = find_root(Path.cwd())
    text = read(root, STORIES_PATH)
    if text is None:
        print(f"error: {STORIES_PATH} not found")
        return 1
    stories = parse_stories(text)
    today = _dt.date.today().isoformat()
    lines = [
        "# Kanban",
        "",
        f"Generated by `wt.py kanban` from `USER_STORIES.md` on {today}. Do not edit by hand.",
    ]
    for status in STATUSES:
        column = [s for s in stories if s.status == status]
        lines += ["", f"## {status} ({len(column)})", ""]
        for story in sorted(column, key=lambda s: (s.sprint_number, int(s.id.split("-")[1]))):
            lines.append(f"- **{story.id}** {story.short_title} · {story.priority} · Sprint {story.sprint}")
    unknown = [s for s in stories if s.status not in STATUSES]
    if unknown:
        lines += ["", f"## Unknown status ({len(unknown)})", ""]
        lines += [f"- **{s.id}** {s.short_title} · status '{s.status}'" for s in unknown]
    target = root / KANBAN_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {KANBAN_PATH} ({len(stories)} stories)")
    return 0


def cmd_sprint(args: argparse.Namespace) -> int:
    root = find_root(Path.cwd())
    config = load_config(root) or {}
    number = str(args.number if args.number is not None else config.get("sprint", {}).get("current", 1))
    text = read(root, STORIES_PATH)
    if text is None:
        print(f"error: {STORIES_PATH} not found")
        return 1
    stories = [s for s in parse_stories(text) if s.in_sprint(number)]
    planned = [s for s in stories if s.status != "Dropped"]
    shipped = [s for s in planned if s.status == "Done"]
    open_ = [s for s in planned if s.status != "Done"]
    dropped = [s for s in stories if s.status == "Dropped"]
    print(f"Sprint {number}: planned {len(planned)} · done {len(shipped)} · not done {len(open_)} · dropped {len(dropped)}")
    print("\nShipped")
    print("\n".join(f"- {s.id} {s.short_title}" for s in shipped) or "- none")
    print("\nNot done (slip to the next sprint with a reason, or keep In progress on its branch)")
    print("\n".join(f"- {s.id} {s.short_title} ({s.status})" for s in open_) or "- none")
    if dropped:
        print("\nDropped")
        print("\n".join(f"- {s.id} {s.short_title}" for s in dropped))
    return 0


def cmd_agreement(args: argparse.Namespace) -> int:
    root = find_root(Path.cwd())
    config = load_config(root)
    if config is None:
        print(f"error: no {CONFIG_NAME} found; run wt.py init first")
        return 1
    branches = config.get("branches", {})
    template = (TEMPLATES / "WORKING_AGREEMENT.md").read_text(encoding="utf-8")
    values = {
        "profile": config.get("profile", "standard"),
        "board": config.get("board", {}).get("tool", "local"),
        "sprint_length": config.get("sprint", {}).get("length", "1 day"),
        "wip_limit": config.get("wip_limit", 2),
        "checkpoints": config.get("checkpoints", "every-step"),
        "story_branch": branches.get("story", "feat/us-{id}-{slug}"),
        "integration": branches.get("integration", "dev"),
        "release": branches.get("release", "main"),
    }
    for key, value in values.items():
        template = template.replace("{" + key + "}", str(value))
    print(template, end="")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="wt.py", description="whole-team project helper")
    sub = parser.add_subparsers(dest="command", required=True)

    init = sub.add_parser("init", help="create config and the profile's documents")
    init.add_argument("--profile", choices=PROFILES, default=None, help="default: standard (on an existing project: change profile)")
    init.add_argument("--board", choices=BOARDS, default=None, help="default: local")
    init.add_argument("--ui", action="store_true", help="the project has screens")
    init.add_argument("--brief", action="store_true", help="work starts from a brief or spec")
    init.add_argument("--assessment", action="store_true", help="assessment or take-home: brief, traceability, AI usage")
    init.add_argument("--trunk", action="store_true", help="trunk-based: story branches merge into main")
    init.add_argument("--checkpoints", choices=CHECKPOINTS, default=None, help="when the agent stops to ask: every-step (default), phase or gates")
    init.add_argument("--sprint-length", default=None, help='for example "1 day", "1 week", "2 weeks" (a bare number means days); default: 1 day')
    init.add_argument("--dir", default=".")
    init.set_defaults(func=cmd_init)

    sub.add_parser("status", help="where the project stands").set_defaults(func=cmd_status)
    lint_parser = sub.add_parser("lint", help="check stories, coverage and documents")
    lint_parser.add_argument("--release", action="store_true", help="release gate: stricter")
    lint_parser.set_defaults(func=cmd_lint)
    sub.add_parser("kanban", help="write KANBAN.md").set_defaults(func=cmd_kanban)
    sprint_parser = sub.add_parser("sprint", help="sprint report: planned, shipped, not done")
    sprint_parser.add_argument("number", nargs="?", type=int, help="default: the current sprint")
    sprint_parser.set_defaults(func=cmd_sprint)
    sub.add_parser("agreement", help="print the working agreement block").set_defaults(func=cmd_agreement)
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
