#!/usr/bin/env python3
"""Turn a `claude plugin eval --json` result into assets/metrics.html (render it with
tools/render_assets.py) and print the summary numbers for README.md and evals/RESULTS.md.

    python3 tools/make_metrics.py path/to/result.json
"""

from __future__ import annotations

import html
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

LABELS = {
    "assessment-pushback": "Scopes a too-big brief",
    "overengineering": "Pushes back on overengineering",
    "intake-board-choice": "Setup asks where stories live",
    "narrow-question": "Splits a too-big story",
    "ambiguity": "Names ambiguity and its cost",
    "change-control": "Mid-sprint change is a trade",
    "push-gate": "Never pushes without a yes",
    "dod-gate": "Failing tests block Done",
    "stay-inside-story": "Fix touches only the story",
    "backlog-story": "Not-ready story gets refined",
    "retro": "Retro with owned actions",
    "sprint-close-slip": "Unfinished story slips honestly",
    "no-trigger-small-edit": "Stays out of small edits",
    "ask-before-build": "Asks before building a story",
    "explain-decision": "Explains a decision before acting",
}


def summarize(data: dict) -> dict:
    rows = []
    fired_runs = fired_total = 0
    for case in data["cases"]:
        agg = case["aggregates"]
        with_runs = case["arms"].get("with", [])
        for run in with_runs:
            for grader in run.get("graders", []):
                if grader.get("name") == "skill-fired" and case["name"] != "no-trigger-small-edit":
                    fired_total += 1
                    fired_runs += 1 if grader.get("passed") else 0
        rows.append({
            "name": case["name"],
            "label": LABELS.get(case["name"], case["name"]),
            "with": agg["score"],
            "without": agg.get("scoreWithout", 0.0),
            "runs": len(with_runs),
        })
    mean_with = sum(r["with"] for r in rows) / len(rows)
    mean_without = sum(r["without"] for r in rows) / len(rows)
    return {
        "rows": rows,
        "mean_with": mean_with,
        "mean_without": mean_without,
        "fired": (fired_runs, fired_total),
        "cost": data.get("costUsd", 0.0),
        "claude": data.get("claudeVersion", ""),
        "started": data.get("startedAt", "")[:10],
    }


def chart(summary: dict, model: str) -> str:
    rows = sorted(summary["rows"], key=lambda r: r["with"] - r["without"], reverse=True)
    bar_w = 520
    items = []
    for r in rows:
        delta = r["with"] - r["without"]
        sign = "+" if delta > 0 else ""
        tone = "up" if delta > 0.001 else ("down" if delta < -0.001 else "flat")
        items.append(f'''
    <div class="row">
      <div class="label">{html.escape(r["label"])}</div>
      <div class="bars">
        <div class="bar without" style="width:{max(r["without"] * bar_w, 3):.0f}px"></div>
        <div class="bar with" style="width:{max(r["with"] * bar_w, 3):.0f}px"></div>
      </div>
      <div class="nums"><span class="w">{r["with"] * 100:.0f}%</span><span class="o">{r["without"] * 100:.0f}%</span><span class="d {tone}">{sign}{delta * 100:.0f}</span></div>
    </div>''')
    fired, total = summary["fired"]
    return f'''<!doctype html>
<!-- Generated by tools/make_metrics.py from a claude plugin eval run. Render: python3 tools/render_assets.py -->
<html><head><meta charset="utf-8"><style>
  :root {{ --bg:#0d0f13; --panel:#151820; --line:#272c38; --text:#f3f4f6; --muted:#9aa3b2; --dim:#6b7383; --accent:#e8744f; --grey:#3a404d; --green:#5fbf85; --red:#e06c6c; }}
  * {{ box-sizing:border-box; margin:0; padding:0; }}
  html, body {{ width:1600px; height:800px; overflow:hidden; }}
  body {{ font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",Inter,Helvetica,Arial,sans-serif; color:var(--text);
    background:radial-gradient(circle at 1px 1px,#1a1e27 1px,transparent 0) 0 0/26px 26px,var(--bg); padding:44px 64px; }}
  h1 {{ font-size:30px; font-weight:700; }} h1 span {{ color:var(--accent); }}
  .meta {{ color:var(--muted); font-size:16px; margin-top:6px; }}
  .stats {{ display:flex; gap:16px; margin-top:26px; }}
  .stat {{ background:var(--panel); border:1px solid var(--line); border-radius:12px; padding:14px 20px; min-width:230px; }}
  .stat b {{ font-size:32px; font-weight:700; display:block; }} .stat b.acc {{ color:var(--accent); }}
  .stat span {{ color:var(--muted); font-size:14.5px; }}
  .legend {{ display:flex; gap:22px; margin-top:26px; color:var(--muted); font-size:15px; align-items:center; }}
  .sw {{ display:inline-block; width:14px; height:14px; border-radius:3px; margin-right:8px; vertical-align:-2px; }}
  .rows {{ margin-top:14px; display:grid; gap:9px; }}
  .row {{ display:grid; grid-template-columns:330px 560px 1fr; align-items:center; gap:18px; }}
  .label {{ font-size:17px; }}
  .bars {{ display:grid; gap:4px; }}
  .bar {{ height:11px; border-radius:3px; }} .bar.with {{ background:var(--accent); }} .bar.without {{ background:var(--grey); }}
  .nums {{ font-family:"SF Mono",Menlo,monospace; font-size:15px; display:flex; gap:18px; color:var(--muted); }}
  .nums .w {{ color:var(--text); width:52px; }} .nums .o {{ width:64px; }} .head {{ margin-top:18px; }} .head .nums, .head .nums .w {{ color:var(--dim); font-size:13px; }}
  .d.up {{ color:var(--green); }} .d.down {{ color:var(--red); }} .d.flat {{ color:var(--dim); }}
</style></head><body>
  <h1>With whole-team vs <span>without</span></h1>
  <div class="meta">{len(rows)} scenarios · {rows[0]["runs"]} runs each per arm · {html.escape(model)} · claude plugin eval, {summary["started"]}</div>
  <div class="stats">
    <div class="stat"><b class="acc">{summary["mean_with"] * 100:.0f}%</b><span>average score with the skill</span></div>
    <div class="stat"><b>{summary["mean_without"] * 100:.0f}%</b><span>same agent, no skill</span></div>
    <div class="stat"><b>{(summary["mean_with"] - summary["mean_without"]) * 100:+.0f} pts</b><span>difference</span></div>
    <div class="stat"><b>{fired}/{total}</b><span>runs where the skill fired</span></div>
  </div>
  <div class="legend"><div><span class="sw" style="background:var(--accent)"></span>with whole-team</div><div><span class="sw" style="background:var(--grey)"></span>without</div><div>score = graders passed, weighted</div></div>
  <div class="row head"><div></div><div></div><div class="nums"><span class="w">with</span><span class="o">without</span><span>change</span></div></div>
  <div class="rows">{"".join(items)}
  </div>
</body></html>
'''


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    data = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    model = sys.argv[2] if len(sys.argv) > 2 else "Claude Sonnet 5"
    summary = summarize(data)
    (ROOT / "assets" / "metrics.html").write_text(chart(summary, model), encoding="utf-8")
    fired, total = summary["fired"]
    print(json.dumps({
        "mean_with": round(summary["mean_with"], 3),
        "mean_without": round(summary["mean_without"], 3),
        "delta_pts": round((summary["mean_with"] - summary["mean_without"]) * 100),
        "fired": f"{fired}/{total}",
        "cost_usd": round(summary["cost"], 2),
        "rows": [(r["name"], round(r["with"], 2), round(r["without"], 2)) for r in summary["rows"]],
    }, indent=1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
