#!/usr/bin/env python3
"""Render the README images from their HTML sources in assets/. Needs Google Chrome or Chromium.

- assets/banner.html    -> assets/banner.png and assets/social-preview.png (1280x640, under 1 MB for GitHub)
- assets/lifecycle.html -> assets/lifecycle.png (1600x900)
- assets/metrics.html   -> assets/metrics.png (1600x800), generated by tools/make_metrics.py

    python3 tools/render_assets.py
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
CANDIDATES = [
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Chromium.app/Contents/MacOS/Chromium",
    "google-chrome",
    "chromium",
    "chromium-browser",
]
# (source, output, width, height, extra copies)
IMAGES = [
    ("banner.html", "social-preview.png", 1280, 640, ["banner.png"]),
    ("lifecycle.html", "lifecycle.png", 1600, 900, []),
    ("metrics.html", "metrics.png", 1600, 800, []),
]


def find_chrome() -> str:
    for candidate in CANDIDATES:
        if Path(candidate).exists() or shutil.which(candidate):
            return candidate
    raise SystemExit("error: Google Chrome or Chromium not found")


def render(chrome: str, source: Path, target: Path, width: int, height: int) -> None:
    subprocess.run(
        [
            chrome,
            "--headless=new",
            "--disable-gpu",
            "--hide-scrollbars",
            "--force-device-scale-factor=1",
            f"--window-size={width},{height}",
            f"--screenshot={target}",
            source.as_uri(),
        ],
        check=True,
        capture_output=True,
    )


def main() -> int:
    chrome = find_chrome()
    status = 0
    for source_name, output, width, height, copies in IMAGES:
        source = ASSETS / source_name
        if not source.is_file():
            continue
        target = ASSETS / output
        render(chrome, source, target, width, height)
        for copy in copies:
            shutil.copyfile(target, ASSETS / copy)
        size = target.stat().st_size
        print(f"wrote assets/{output} ({size // 1024} KB)" + (f" + {', '.join(copies)}" if copies else ""))
        if size >= 1_000_000:
            print(f"error: assets/{output} is over 1 MB", file=sys.stderr)
            status = 1
    return status


if __name__ == "__main__":
    sys.exit(main())
